### ISSUE TITLE
Error 0658 during compilation

### ISSUE THREAD

**Issue by pedipanol** [undisbeliever/terrific-audio-driver#18]
Hi! Thanks for your work on terrific audio driver! It's a pretty fun program to use!

I started getting the following error when trying to compile tad versions 0.0.12 and 0.0.13 on PopOS! (Ubuntu 22.04). 0.0.11 still compiles fine.

```
   Compiling relative-path v1.9.3
error[E0658]: exclusive range pattern syntax is experimental
   --> crates/compiler/src/mml/bc_generator.rs:197:17
    |
197 |                 MIN_TWO_INSTRUCTIONS..MIN_THREE_INSTRUCTIONS => {
    |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: see issue #37854 <https://github.com/rust-lang/rust/issues/37854> for more information
    = help: use an inclusive range pattern, like N..=M

For more information about this error, try `rustc --explain E0658`.
error: could not compile `compiler` (lib) due to 1 previous error
warning: build failed, waiting for other jobs to finish...
```

**Comment by KungFuFurby** [comment]
What is your rust version, just out of curiosity? Type in `rustc --version`. It compiles fine on `rustc 1.81.0`.

**Comment by undisbeliever** [comment]
I did not realise exclusive range pattern syntax was a recent feature.  That was added to rust 1.80.0 (released July 2024).

Looks like Ubuntu 24.04LTS's default rust compiler is [1.75.0](https://packages.ubuntu.com/noble/cargo).   There is a [cargo-1.80](https://packages.ubuntu.com/noble/devel/cargo-1.80) in the package list that should compile TAD.

I would like to support older versions of rust so it works out-of-the-box on Ubuntu.

Give me a few hours to download multiple versions of rust on my laptop and run [cargo-msrv](https://github.com/foresterre/cargo-msrv) to find what's needed to get TAD compiling on an older version of rust.

**Comment by undisbeliever** [comment]
The Terrific Audio Driver now compiles on Windows x64 with rust 1.75.0

@pedipanol can please you let me know if you can compile TAD using the main branch.

**Comment by pedipanol** [comment]
Just saw the replies but in good time. The fix works and I could compile it with rust 1.79.0, everything works!

Thank you so much!

**Comment by undisbeliever** [comment]
No worries.  Thank you for reporting the compile error.

I'm glad you like my audio driver.
